### ISSUE TITLE
TinyMCE & Responsive

### ISSUE THREAD

**Issue by HannesOberreiter** [trippo/ResponsiveFilemanager#235]
Is there a solution to make the ResponsiveFilemanager more mobile friendly as TinyMCE plugin?

Here is a gif how it looks at the moment:
![tinymce_responsive](https://cloud.githubusercontent.com/assets/16878981/12550715/d038532a-c365-11e5-885f-aea1d2668908.gif)

Cheers
Hannes

**Comment by HannesOberreiter** [comment]
I changed a little the css now it looks better.

```css
 .mce-window iframe {
     width: inherit;
     min-height: 500px;
     height: 100%;
 }
```

Cheers
Hannes
